# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487210635529ca5facbdb7a4a7d8cf7eed6fe4043d4b5629df43bddc3e18e585297c9ead39aeb83a9feb257dd692147bb617105168da800d63b4d5a68af5282d

test:
  secret_key_base: cee6560dd804e61e970a54541fb81daf608d3d684b2509b2588141769192ec2faf8a050f9c638dd30b6ea061cea1838fa624940969c7f6fbbfc0cbbda510d97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
